name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: ./action-a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}